package com.adshow.player.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.adshow.player.bean.Advertising;
import com.adshow.player.bean.History;
import com.adshow.player.bean.Schedule;

import com.adshow.player.dao.AdvertisingDao;
import com.adshow.player.dao.HistoryDao;
import com.adshow.player.dao.ScheduleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig advertisingDaoConfig;
    private final DaoConfig historyDaoConfig;
    private final DaoConfig scheduleDaoConfig;

    private final AdvertisingDao advertisingDao;
    private final HistoryDao historyDao;
    private final ScheduleDao scheduleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        advertisingDaoConfig = daoConfigMap.get(AdvertisingDao.class).clone();
        advertisingDaoConfig.initIdentityScope(type);

        historyDaoConfig = daoConfigMap.get(HistoryDao.class).clone();
        historyDaoConfig.initIdentityScope(type);

        scheduleDaoConfig = daoConfigMap.get(ScheduleDao.class).clone();
        scheduleDaoConfig.initIdentityScope(type);

        advertisingDao = new AdvertisingDao(advertisingDaoConfig, this);
        historyDao = new HistoryDao(historyDaoConfig, this);
        scheduleDao = new ScheduleDao(scheduleDaoConfig, this);

        registerDao(Advertising.class, advertisingDao);
        registerDao(History.class, historyDao);
        registerDao(Schedule.class, scheduleDao);
    }
    
    public void clear() {
        advertisingDaoConfig.clearIdentityScope();
        historyDaoConfig.clearIdentityScope();
        scheduleDaoConfig.clearIdentityScope();
    }

    public AdvertisingDao getAdvertisingDao() {
        return advertisingDao;
    }

    public HistoryDao getHistoryDao() {
        return historyDao;
    }

    public ScheduleDao getScheduleDao() {
        return scheduleDao;
    }

}
