package com.adshow.player.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.adshow.player.bean.Schedule;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SCHEDULE".
*/
public class ScheduleDao extends AbstractDao<Schedule, String> {

    public static final String TABLENAME = "SCHEDULE";

    /**
     * Properties of entity Schedule.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property ScheduleTime = new Property(1, java.util.Date.class, "scheduleTime", false, "SCHEDULE_TIME");
        public final static Property AdvertisingId = new Property(2, String.class, "advertisingId", false, "ADVERTISING_ID");
    }

    private Query<Schedule> advertising_SchedulesQuery;

    public ScheduleDao(DaoConfig config) {
        super(config);
    }
    
    public ScheduleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SCHEDULE\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"SCHEDULE_TIME\" INTEGER," + // 1: scheduleTime
                "\"ADVERTISING_ID\" TEXT NOT NULL );"); // 2: advertisingId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SCHEDULE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Schedule entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        java.util.Date scheduleTime = entity.getScheduleTime();
        if (scheduleTime != null) {
            stmt.bindLong(2, scheduleTime.getTime());
        }
        stmt.bindString(3, entity.getAdvertisingId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Schedule entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        java.util.Date scheduleTime = entity.getScheduleTime();
        if (scheduleTime != null) {
            stmt.bindLong(2, scheduleTime.getTime());
        }
        stmt.bindString(3, entity.getAdvertisingId());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public Schedule readEntity(Cursor cursor, int offset) {
        Schedule entity = new Schedule( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)), // scheduleTime
            cursor.getString(offset + 2) // advertisingId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Schedule entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setScheduleTime(cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)));
        entity.setAdvertisingId(cursor.getString(offset + 2));
     }
    
    @Override
    protected final String updateKeyAfterInsert(Schedule entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(Schedule entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Schedule entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "schedules" to-many relationship of Advertising. */
    public List<Schedule> _queryAdvertising_Schedules(String advertisingId) {
        synchronized (this) {
            if (advertising_SchedulesQuery == null) {
                QueryBuilder<Schedule> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.AdvertisingId.eq(null));
                advertising_SchedulesQuery = queryBuilder.build();
            }
        }
        Query<Schedule> query = advertising_SchedulesQuery.forCurrentThread();
        query.setParameter(0, advertisingId);
        return query.list();
    }

}
